# Generated by Django 5.0.6 on 2024-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_subscriptions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='permssions',
            field=models.ManyToManyField(limit_choices_to={'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
