# Generated by Django 5.0.6 on 2024-07-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0007_alter_subscriptions_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm')], 'verbose_name': 'Subscription'},
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
