# Generated by Django 5.0.6 on 2024-07-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisits',
            options={'verbose_name': 'Page visits'},
        ),
    ]
